# Start from the latest Ubuntu base image
FROM ubuntu:latest

# Update package lists and install basic packages
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    python3 \
    python3-pip \
    libboost-all-dev \
    wget \
    clang \
    lld \
    llvm \
    libomp-dev \
    libopenblas-dev \
    liblapack-dev \
    && rm -rf /var/lib/apt/lists/*

# Install gdb
RUN apt-get update && apt-get install -y \
    gdb \
    && rm -rf /var/lib/apt/lists/*

# Install Eigen
RUN apt-get update && apt-get install -y \
    libeigen3-dev \
    && rm -rf /var/lib/apt/lists/*

# Make a working directory
WORKDIR /workspace

# Default command when container starts
CMD ["/bin/bash"]
