# Start from the latest Ubuntu base image
FROM ubuntu:latest

# Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

# Update apt packages
RUN apt-get update

# Install build tools and development essentials
RUN apt-get -y install \
    build-essential \
    git \
    cmake \
    ninja-build \
    ccache \
    valgrind

# Install math libraries
RUN apt-get -y install \
    libblas-dev \
    liblapack-dev \
    libfftw3-dev \
    libopenblas-dev

# Install HDF5 libraries
RUN apt-get -y install \
    libhdf5-serial-dev \
    hdf5-tools

# Install Python and related packages
RUN apt-get -y install \
    python3 \
    python3-pip \
    python3-numpy \
    python3-pybind11 \
    pybind11-dev

# Install compilers and compiler tools
RUN apt-get -y install \
    clang \
    lld \
    llvm \
    libomp-dev

# Install additional libraries and utilities
RUN apt-get -y install \
    libboost-all-dev \
    catch2 \
    lsb-release \
    wget \
    gdb \
    lldb \
    software-properties-common

# Install Eigen
RUN apt-get -y install libeigen3-dev

# Install Intel oneAPI
RUN if [ "$TARGETARCH" = "amd64" ]; then \
    curl -fsSL https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB | gpg --dearmor | tee /usr/share/keyrings/intel-oneapi-archive-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/intel-oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main " > /etc/apt/sources.list.d/oneAPI.list \
    && apt-get update \
    && apt-get upgrade -y \
    && \
    apt-get install -y --no-install-recommends \
      pkg-config gnupg libarchive13 wget net-tools intel-basekit intel-hpckit; \
    fi

# Cleanup the image
RUN apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

# Set links to solve ninja dependencies when compiling
RUN ln -s /usr/include /include

# Make a working directory
WORKDIR /workspace

# Default command when container starts
CMD ["/bin/bash"]